### ISSUE TITLE
Build single js file and single css file like Svelte does

### ISSUE THREAD

**Issue by kauaicreative** [idleberg/sveltekit-adapter-html-like#1]
Build single js file and single css file like Svelte does
This makes embedding into wordpress much simpler.
Wondering if this functionality is on the roadmap - https://github.com/sveltejs/kit/issues/3882

**Comment by idleberg** [comment]
While I understand your use case, let me question it for the sake of caching. Wouldn't you *really* prefer an easier way to embed your assets into WordPress? I have been using a script reading the Vite manifest for a little while now. I found it so useful that I published it on Packagist.

https://github.com/idleberg/php-wordpress-vite-assets

Otherwise I'd prefer following `@sveltejs/adapter-static` for the base features.

**Comment by kauaicreative** [comment]
I'll take a look at this. Thanks!
